# Site settings
title: My First Jekyll Project
email: jharwood@harwoodspike.com
description: > # this means to ignore newlines until "baseurl:"
  New site description text.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harwoodspike.com" # the base hostname & protocol for your site
twitter_username: harwoodspike
github_username:  harwoodspike

# Build settings
markdown: kramdown

theme: jekyll-theme-modernist